### ISSUE TITLE
Invalid htlc-stream json

### ISSUE THREAD

**Issue by dutchpool** [smallworlnd/stream-lnd-htlcs#12]
The lines in the htlc-stream.json file are not in valid json, which prevents me from easily processing the results. Single quotes are used vs. double quotes and backslashes aren't escaped (occur for example in the node alias).

Could you parse it to valid json, perhaps something like this?

stream-lnd-htlcs.py#28
```
import json

...

for response in lnd.get_htlc_events():
    htlc = Htlc(lnd, response, args.humandates)
    dumped_htlc = json.dumps(htlc.__dict__)
    if args.silent == "false":
        print(dumped_htlc)
    if args.streammode == "false":
        with open(args.outfile, 'a') as f:
            print(dumped_htlc, file=f)
```

**Comment by smallworlnd** [comment]
That's correct, the output isn't true json, but rather a python dictionary. I didn't modify the output format from the raw API call. I'd be happy to accept a PR to convert streamed output to proper json!

**Comment by dutchpool** [comment]
#13

**Comment by smallworlnd** [comment]
Fixed in PR https://github.com/smallworlnd/stream-lnd-htlcs/commit/e7bfed136760d910a86f48deb747cafaab676948
