### ISSUE TITLE
Add incoming_channel_id and outgoing_channel_id

### ISSUE THREAD

**Issue by Deekee62** [smallworlnd/stream-lnd-htlcs#15]
Unfortunately the incoming_channel_id and outgoing_channel_id are not logged in htlc-stream.json. Users tend to change their node alias and it would be very help full to those two.

**Comment by smallworlnd** [comment]
Done! You now have both channel and HTLC ID fields per line. Note that the key string for aliases has been slightly modified for clearer separation from channel IDs: https://github.com/smallworlnd/stream-lnd-htlcs/commit/6d9811c7eddc4a765fb11e953857133ac672a8b6
